### PR TITLE
WIP - Sidebar prototype

### PR DESCRIPTION
**Pull request by Maxbrain0**
I have added a sidebar story in /src/components/global/sidebar/

Thus far, I have added a sidebar menu conforming as best as possible to #51 (a few icons are different as I couldn't find them in FA Pro). I used the required fonts, sizes, and colors, but please verify (I found it weird the colors we slightly off the main theme colors 🤷‍♂. 

### Functionality

If a menu item as a "sub-menu", hovering over that item will reveal the sub menu. I also made sure to properly align items missing an icon. A boolean prop (isOpen) can also be provided to toggle the UI-Kit off-canvas style which has a slide animation by default. If there's a way to show this animation in storybook, let me know. 

Clicking on any menu item will call the onNavigate method provided on props which is linked to a storybook action. We could in the end just use Nextjs router or set the link inside of the Sidebar component, but making that change would be easy. 

TODO / Questions:
- [ ] How should we handle "subMenus" for mobile? Will we assume that if the user activates a main menu item, the activated route component will have links to submenu items?
- [ ] Test on mobile
- [ ] Do we handle navigation in a parent component or directly in the sidebar?
- [ ] Better way to handle subMenu placement using CSS only? Right now I'm using JS. We need to verify subMenus overlay the main content.

### CODE REVIEW

**Comment by lloan** [comment]
Ah, it MIGHT be because its in WIP. Hm... odd. Will review this too.

**Comment by Maxbrain0** [comment]
@lloan, good deal. I appreciate any feedback!

**Comment by Maxbrain0** [comment]
@dhuan008, Thanks for reviewing. I may post some updates. I didn't realize the linting rules weren't working properly while only using storybook. So I'll push with a few minor linting updates.

**Comment by Maxbrain0** [comment]
@dhuan008 and @saynegrojas, I updated the scss file to meet the Stylelint config in the project.

When running storybook, the linter is not run as it is when using yarn dev. Anyhow, I found installing the styelint plugin for VSCode very helpful (in case this helps you in the future).

**Comment by lloan** [comment]
will test on `dev` -> spark-dev.iesd.com

**Pull request merged**
