### PR TITLE
 Dashboard page andy -AddCourse

### PR DESCRIPTION
**Pull request by Andymendez100**

### CODE REVIEW

**Comment by lloan** [comment]
@Andymendez100  what is this missing - just mobile responsiveness to get work started on the backend?

**Comment by lloan** [comment]
@Andymendez100 is this mobile-friendly yet? Or is this one that you need to offload? Let me know - thanks!

**Comment by lloan** [comment]
@dhuan008 can you please check this branch out and see what is missing? Check for responsiveness and check if anything is broken layout-wise. Thanks!

**Comment by Andymendez100** [comment]
Sorry, Didn't notice comments. Responsiveness and functionality. But both are blocked by file drag concept I am implementing. Still WIP

**Comment by Andymendez100** [comment]
Pushing this through so @VelazquezLuis can work on Media queries for page

**Pull request merged**
